---
metadata:
  name: "Check that all resources are tagged with the key - environment"
  id: "CHECK_TAG_ENVIRONMENT"
  category: "GENERAL_SECURITY"
scope:
  provider: aws
definition:
  cond_type: "attribute"
  resource_types:
    - "all"
  attribute: "tags.environment"
  operator: "subset"
  value:
    - "dev"
    - "prod"
    - "test"

